# Generated by Django 5.0.4 on 2024-07-25 17:57

import api.models.usuario
import api.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_empresa",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_empresa", models.TextField()),
                ("nro_cnpj", models.TextField()),
                ("razao_social", models.TextField(blank=True, null=True)),
                ("descricao", models.TextField(null=True)),
                ("nome_responsavel", models.TextField()),
                ("cargo", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("nro_cpf", models.TextField()),
                ("telefone", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                ("id_endereco", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("bairro", models.CharField(max_length=100, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                ("estado", models.CharField(max_length=50, null=True)),
                ("codigo_postal", models.CharField(max_length=30, null=True)),
                ("descricao", models.TextField(max_length=500, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_historico",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("usuario", models.UUIDField(verbose_name=api.models.usuario.Usuario)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_cliente",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=20, null=True)),
                ("ultima_compra", models.DateField(blank=True, null=True)),
                (
                    "tipo_cliente",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("descricao", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresa",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.endereco",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                ("id_loja", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
                ("numero_telefone", models.CharField(max_length=50, null=True)),
                ("horario_operacao_inicio", models.TimeField(blank=True, null=True)),
                ("horario_operacao_fim", models.TimeField(blank=True, null=True)),
                ("segunda", models.BooleanField(default=False)),
                ("terca", models.BooleanField(default=False)),
                ("quarta", models.BooleanField(default=False)),
                ("quinta", models.BooleanField(default=False)),
                ("sexta", models.BooleanField(default=False)),
                ("sabado", models.BooleanField(default=False)),
                ("domingo", models.BooleanField(default=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.empresa"
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.endereco",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Galao",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                ("id_galao", models.AutoField(primary_key=True, serialize=False)),
                ("data_validade", models.CharField(max_length=50, null=True)),
                ("data_fabricacao", models.CharField(max_length=50, null=True)),
                ("descricao", models.TextField(null=True)),
                ("quantidade", models.IntegerField(default=0)),
                ("titulo", models.CharField(max_length=100, null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.loja",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Motoboy",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_motoboy",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.empresa",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PDV",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_pdv",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255, null=True)),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "status_operacao",
                    models.IntegerField(
                        choices=[
                            (3, "Bloqueado"),
                            (0, "Excluído"),
                            (1, "Aberto"),
                            (2, "Fechado"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.loja"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_produto",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("quantidade_atual_estoque", models.IntegerField(null=True)),
                ("quantidade_minima_estoque", models.IntegerField(null=True)),
                ("codigo", models.PositiveIntegerField(editable=False, unique=True)),
                ("is_retornavel", models.BooleanField(blank=True, null=True)),
                ("status", models.BooleanField(blank=True, default=True, null=True)),
                (
                    "data_validade",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=50
                    ),
                ),
                (
                    "preco_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fabricante", models.CharField(max_length=100, null=True)),
                ("descricao", models.TextField(null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.loja"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemCompra",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_item_compra",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "valor_unidade",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.produto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistroDiarioPDV",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_registro_diario",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "saldo_inicial_dinheiro",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "saldo_final_dinheiro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "saldo_final_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "maquina_tipo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "saldo_final_maquina",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "horario_iniciou",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "horario_fechamento",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "descricao_interna",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "pdv",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pdv",
                    ),
                ),
            ],
            options={
                "unique_together": {("pdv", "dia")},
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_usuario",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_completo", models.CharField(max_length=255)),
                ("nome_usuario", models.CharField(max_length=50)),
                ("senha", models.CharField(max_length=200)),
                ("nivel_usuario", models.IntegerField()),
                ("status_acesso", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=255)),
                ("ultimo_login", models.DateTimeField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.empresa"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sessao",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                ("id_sessao", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("ip_sessao", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200, null=True)),
                ("pagina_atual", models.CharField(max_length=200, null=True)),
                ("time_iniciou", models.DateTimeField(null=True)),
                ("status", models.BooleanField(default=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("regiao", models.CharField(blank=True, max_length=100, null=True)),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "organizacao",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Personalizacao",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_personalizacao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chave", models.CharField(max_length=255)),
                ("valor", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
                ("descricao_interna", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=255)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_log",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("origem", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ip_usuario", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricoAlteracoes",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_historico",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entidade", models.CharField(max_length=100)),
                ("entidade_id", models.UUIDField()),
                ("tipo_alteracao", models.CharField(max_length=50)),
                (
                    "campo_alterado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("valor_antigo", models.TextField(blank=True, null=True)),
                ("valor_novo", models.TextField(blank=True, null=True)),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        default=api.utils.Utils.obter_data_hora_atual, editable=False
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_configuracao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.IntegerField(null=True)),
                ("titulo", models.TextField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("descricao_interna", models.TextField(blank=True, null=True)),
                ("status_acesso", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssociadoPDV",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_associado",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_acesso", models.BooleanField(null=True)),
                (
                    "pdv",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pdv",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Associado",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_associado",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status_acesso", models.BooleanField(null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.loja",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_venda",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_venda",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Dinheiro"),
                            (2, "Máquina de Crédito"),
                            (3, "Máquina de Débito"),
                            (4, "PIX"),
                            (5, "Fiado"),
                            (6, "Boleto"),
                        ],
                        null=True,
                    ),
                ),
                ("forma_pagamento", models.CharField(max_length=50)),
                ("estado_transacao", models.CharField(max_length=20, null=True)),
                (
                    "metodo_entrega",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("desconto", models.CharField(blank=True, max_length=50, null=True)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_entrega",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "troco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "nota_fiscal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.cliente",
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.loja"
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(
                        blank=True, through="api.ItemCompra", to="api.produto"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TransacaoPDV",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_transacao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "tipo_operacao",
                    models.IntegerField(
                        blank=True, choices=[(1, "Entrou"), (2, "Retirado")], null=True
                    ),
                ),
                (
                    "tipo_pagamento",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Dinheiro"),
                            (2, "Máquina de Crédito"),
                            (3, "Máquina de Débito"),
                            (4, "PIX"),
                            (5, "Fiado"),
                            (6, "Boleto"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "registro_diario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.registrodiariopdv",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.venda",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="itemcompra",
            name="venda",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.venda"
            ),
        ),
        migrations.CreateModel(
            name="GestaoGalao",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_gestao_galao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("descricao", models.TextField(null=True)),
                (
                    "galao_entrando",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galao_entrando_set",
                        to="api.galao",
                    ),
                ),
                (
                    "galao_saiu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galao_saiu_set",
                        to="api.galao",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.venda",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                ("_insert", models.DateTimeField(auto_now_add=True)),
                ("_update", models.DateTimeField(auto_now=True)),
                (
                    "id_entrega",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor_entrega", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_pedido", models.TimeField(blank=True, null=True)),
                ("time_finalizacao", models.TimeField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "motoboy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.motoboy",
                    ),
                ),
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrega",
                        to="api.venda",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
