# Generated by Django 5.0.4 on 2024-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="status",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
