# Generated by Django 5.0.4 on 2024-05-30 13:58

import api.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_produto_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transacao",
            name="caixa",
        ),
        migrations.RemoveField(
            model_name="transacao",
            name="venda",
        ),
        migrations.CreateModel(
            name="PDV",
            fields=[
                (
                    "id_caixa",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255, null=True)),
                ("dia", models.CharField(editable=False, max_length=50, null=True)),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=100
                    ),
                ),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.loja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Associado_PDV",
            fields=[
                (
                    "id_associado",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=100
                    ),
                ),
                ("status_acesso", models.BooleanField(null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.usuario",
                    ),
                ),
                (
                    "pdv",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pdv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transacao_PDV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=100
                    ),
                ),
                (
                    "PDV",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pdv",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.venda",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Caixa",
        ),
        migrations.DeleteModel(
            name="Transacao",
        ),
    ]
