# Generated by Django 5.0.4 on 2024-05-30 15:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_transacao_caixa_remove_transacao_venda_pdv_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pdv",
            old_name="id_caixa",
            new_name="id_pdv",
        ),
    ]
