# Generated by Django 5.0.4 on 2024-05-31 13:03

import api.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_rename_id_caixa_pdv_id_pdv"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Associado_PDV",
            new_name="AssociadoPDV",
        ),
        migrations.RemoveField(
            model_name="pdv",
            name="dia",
        ),
        migrations.RemoveField(
            model_name="pdv",
            name="saldo_final",
        ),
        migrations.AddField(
            model_name="pdv",
            name="status_operacao",
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name="HistoricoAlteracoes",
            fields=[
                (
                    "id_historico",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entidade", models.CharField(max_length=100)),
                ("entidade_id", models.UUIDField()),
                ("tipo_alteracao", models.CharField(max_length=50)),
                (
                    "campo_alterado",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("valor_antigo", models.TextField(blank=True, null=True)),
                ("valor_novo", models.TextField(blank=True, null=True)),
                (
                    "data_alteracao",
                    models.DateTimeField(
                        default=api.utils.Utils.obter_data_hora_atual, editable=False
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroDiarioPDV",
            fields=[
                (
                    "id_registro_diario",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dia", models.CharField(editable=False, max_length=50, null=True)),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("status_operacao", models.BooleanField(null=True)),
                ("horario_iniciou", models.CharField(editable=False, max_length=50)),
                ("horario_fechamento", models.CharField(editable=False, max_length=50)),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=100
                    ),
                ),
                (
                    "pdv",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.pdv",
                    ),
                ),
            ],
            options={
                "unique_together": {("pdv", "dia")},
            },
        ),
        migrations.CreateModel(
            name="TransacaoPDV",
            fields=[
                (
                    "id_transacao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=100)),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=100
                    ),
                ),
                (
                    "registro_diario",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.registrodiariopdv",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.venda",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Transacao_PDV",
        ),
    ]
