# Generated by Django 5.0.4 on 2024-06-05 19:44

import api.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_associado_pdv_associadopdv_remove_pdv_dia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrodiariopdv",
            name="saldo_final",
        ),
        migrations.RemoveField(
            model_name="registrodiariopdv",
            name="saldo_inicial",
        ),
        migrations.RemoveField(
            model_name="registrodiariopdv",
            name="status_operacao",
        ),
        migrations.AddField(
            model_name="registrodiariopdv",
            name="maquina_tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="registrodiariopdv",
            name="saldo_final_dinheiro",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="registrodiariopdv",
            name="saldo_final_maquina",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="registrodiariopdv",
            name="saldo_inicial_dinheiro",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="associadopdv",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="registrodiariopdv",
            name="dia",
            field=models.CharField(
                default=api.utils.Utils.obter_data_hora_atual,
                editable=False,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registrodiariopdv",
            name="horario_fechamento",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="registrodiariopdv",
            name="horario_iniciou",
            field=models.CharField(
                default=api.utils.Utils.obter_data_hora_atual,
                editable=False,
                max_length=50,
            ),
        ),
    ]
