# Generated by Django 5.0.4 on 2024-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_remove_registrodiariopdv_saldo_final_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrodiariopdv",
            name="saldo_final_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
