# Generated by Django 5.0.4 on 2024-06-07 18:14

import api.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_registrodiariopdv_saldo_final_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="empresa",
            name="id",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="id",
        ),
        migrations.AlterField(
            model_name="empresa",
            name="id_empresa",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="id_usuario",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.CreateModel(
            name="Personalizacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chave", models.CharField(max_length=255)),
                ("valor", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
                ("descricao_interna", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=255)),
                (
                    "insert",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual,
                        editable=False,
                        max_length=100,
                    ),
                ),
                (
                    "update",
                    models.CharField(
                        default=api.utils.Utils.obter_data_hora_atual, max_length=100
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
                    ),
                ),
            ],
        ),
    ]
