# Generated by Django 5.0.4 on 2024-06-24 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_pdv_status_operacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="transacaopdv",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="pdv",
            name="status_operacao",
            field=models.IntegerField(
                choices=[
                    (3, "Bloqueado"),
                    (0, "Excluído"),
                    (1, "Aberto"),
                    (2, "Fechado"),
                ],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="transacaopdv",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.venda",
            ),
        ),
    ]
