# Generated by Django 5.0.4 on 2024-07-08 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_remove_transacaopdv_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loja",
            old_name="nome_loja",
            new_name="nome",
        ),
    ]
