# Generated by Django 5.0.4 on 2024-07-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_rename_nome_loja_loja_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associado",
            name="loja",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.loja"
            ),
        ),
        migrations.AlterField(
            model_name="associado",
            name="usuario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="associadopdv",
            name="pdv",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.pdv"
            ),
        ),
        migrations.AlterField(
            model_name="associadopdv",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="empresa",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.empresa"
            ),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="configuracao",
            name="usuario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="motoboy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.motoboy",
            ),
        ),
        migrations.AlterField(
            model_name="entrega",
            name="venda",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entrega",
                to="api.venda",
            ),
        ),
        migrations.AlterField(
            model_name="galao",
            name="loja",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.loja"
            ),
        ),
        migrations.AlterField(
            model_name="gestaogalao",
            name="galao_entrando",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galao_entrando_set",
                to="api.galao",
            ),
        ),
        migrations.AlterField(
            model_name="gestaogalao",
            name="galao_saiu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galao_saiu_set",
                to="api.galao",
            ),
        ),
        migrations.AlterField(
            model_name="gestaogalao",
            name="venda",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.venda"
            ),
        ),
        migrations.AlterField(
            model_name="historicoalteracoes",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="itemcompra",
            name="produto",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.produto"
            ),
        ),
        migrations.AlterField(
            model_name="itemcompra",
            name="venda",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.venda"
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.usuario",
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.empresa"
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="endereco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="motoboy",
            name="empresa",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.empresa"
            ),
        ),
        migrations.AlterField(
            model_name="pdv",
            name="loja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.loja"
            ),
        ),
        migrations.AlterField(
            model_name="personalizacao",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="loja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.loja"
            ),
        ),
        migrations.AlterField(
            model_name="registrodiariopdv",
            name="pdv",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.pdv",
            ),
        ),
        migrations.AlterField(
            model_name="sessao",
            name="usuario",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.usuario"
            ),
        ),
        migrations.AlterField(
            model_name="transacaopdv",
            name="registro_diario",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.registrodiariopdv",
            ),
        ),
        migrations.AlterField(
            model_name="transacaopdv",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.venda",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.empresa"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="loja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.loja"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="produtos",
            field=models.ManyToManyField(
                blank=True, through="api.ItemCompra", to="api.produto"
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.usuario",
            ),
        ),
    ]
