# Generated by Django 5.0.2 on 2024-04-16 15:51

import app.models.cliente
import app.models.usuario
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("id_empresa", models.AutoField(primary_key=True, serialize=False)),
                ("nome_empresa", models.TextField()),
                ("nro_cnpj", models.TextField()),
                ("razao_social", models.TextField(blank=True, null=True)),
                ("descricao", models.TextField(null=True)),
                ("nome_responsavel", models.TextField()),
                ("cargo", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("nro_cpf", models.TextField()),
                ("telefone", models.TextField()),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id_endereco", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("bairro", models.CharField(max_length=100, null=True)),
                ("cidade", models.CharField(max_length=100, null=True)),
                ("estado", models.CharField(max_length=50, null=True)),
                ("codigo_postal", models.CharField(max_length=30, null=True)),
                ("descricao", models.TextField(max_length=500, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Historico",
            fields=[
                (
                    "id_historico",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("usuario", models.UUIDField(verbose_name=app.models.usuario.Usuario)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=255)),
                ("telefone_cliente", models.CharField(max_length=20, null=True)),
                ("ultima_compra", models.DateField(blank=True, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
                (
                    "tipo_cliente",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "descricao_cliente",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.empresa",
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                ("id_loja", models.AutoField(primary_key=True, serialize=False)),
                ("nome_loja", models.CharField(max_length=255)),
                ("numero_telefone", models.CharField(max_length=50, null=True)),
                ("horario_operacao_inicio", models.TimeField(blank=True, null=True)),
                ("horario_operacao_fim", models.TimeField(blank=True, null=True)),
                ("segunda", models.BooleanField(default=False)),
                ("terca", models.BooleanField(default=False)),
                ("quarta", models.BooleanField(default=False)),
                ("quinta", models.BooleanField(default=False)),
                ("sexta", models.BooleanField(default=False)),
                ("sabado", models.BooleanField(default=False)),
                ("domingo", models.BooleanField(default=False)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.empresa"
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Galao",
            fields=[
                ("id_galao", models.AutoField(primary_key=True, serialize=False)),
                ("data_validade", models.CharField(max_length=50, null=True)),
                ("data_fabricacao", models.CharField(max_length=50, null=True)),
                ("descricao", models.TextField(null=True)),
                ("quantidade", models.IntegerField(default=0)),
                ("titulo", models.CharField(max_length=100, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.loja",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Caixa",
            fields=[
                (
                    "id_caixa",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "saldo_inicial",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, null=True
                    ),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.loja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Motoboy",
            fields=[
                (
                    "id_motoboy",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id_produto",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("quantidade_atual_estoque", models.IntegerField(null=True)),
                ("quantidade_minima_estoque", models.IntegerField(null=True)),
                ("codigo", models.IntegerField(null=True)),
                ("is_retornavel", models.BooleanField(blank=True, null=True)),
                ("data_validade", models.DateField(blank=True, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "preco_compra",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fabricante", models.CharField(max_length=100, null=True)),
                ("descricao", models.TextField(null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.loja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCompra",
            fields=[
                (
                    "id_item_compra",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(blank=True, null=True)),
                (
                    "produto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome_completo", models.CharField(max_length=255)),
                ("nome_usuario", models.CharField(max_length=50)),
                ("senha", models.CharField(max_length=200)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
                ("nivel_usuario", models.IntegerField()),
                ("status_acesso", models.BooleanField(default=False)),
                ("email", models.EmailField(max_length=255)),
                ("ultimo_login", models.DateTimeField(null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sessao",
            fields=[
                ("id_sessao", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("ip_sessao", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200, null=True)),
                ("pagina_atual", models.CharField(max_length=200, null=True)),
                (
                    "time_iniciou",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("status", models.BooleanField(default=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
                ("cidade", models.CharField(blank=True, max_length=100, null=True)),
                ("regiao", models.CharField(blank=True, max_length=100, null=True)),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codigo_postal",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "organizacao",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id_log",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("origem", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("ip_usuario", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id_configuracao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.IntegerField(null=True)),
                ("titulo", models.TextField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("descricao_interna", models.TextField(blank=True, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("status_acesso", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Associado",
            fields=[
                (
                    "id_associado",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("status_acesso", models.BooleanField(null=True)),
                (
                    "loja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.loja",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id_venda",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_venda", models.DateField(default=django.utils.timezone.now)),
                ("forma_pagamento", models.CharField(max_length=50)),
                ("estado_transacao", models.CharField(max_length=20, null=True)),
                (
                    "metodo_entrega",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("desconto", models.CharField(blank=True, max_length=50, null=True)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_entrega",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "troco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.UUIDField(
                        null=True, verbose_name=app.models.cliente.Cliente
                    ),
                ),
                (
                    "nota_fiscal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.loja"
                    ),
                ),
                (
                    "produtos",
                    models.ManyToManyField(
                        blank=True, through="app.ItemCompra", to="app.produto"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.usuario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=100)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "caixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.caixa"
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.venda",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemcompra",
            name="venda",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.venda"
            ),
        ),
        migrations.CreateModel(
            name="GestaoGalao",
            fields=[
                (
                    "id_gestao_galao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(null=True)),
                ("descricao", models.TextField(null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.cliente",
                    ),
                ),
                (
                    "galao_entrando",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galao_entrando_set",
                        to="app.galao",
                    ),
                ),
                (
                    "galao_saiu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galao_saiu_set",
                        to="app.galao",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.venda",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id_entrega",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor_entrega", models.DecimalField(decimal_places=2, max_digits=10)),
                ("time_pedido", models.TimeField(blank=True, null=True)),
                ("time_finalizacao", models.TimeField(blank=True, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(auto_now=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "motoboy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.motoboy",
                    ),
                ),
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrega",
                        to="app.venda",
                    ),
                ),
            ],
        ),
    ]
