# Generated by Django 5.0.2 on 2024-02-16 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id_empresa",
                    models.AutoField(
                        db_column="id_empresa", primary_key=True, serialize=False
                    ),
                ),
                ("nome_empresa", models.TextField(db_column="nome_empresa")),
                ("nro_cnpj", models.TextField(db_column="nro_cnpj_empresa")),
                (
                    "razao_social",
                    models.TextField(
                        blank=True, db_column="razao_social_empresa", null=True
                    ),
                ),
                (
                    "descricao",
                    models.TextField(db_column="descricao_empresa", null=True),
                ),
                ("nome_responsavel", models.TextField(db_column="nome_responsavel")),
                ("cargo", models.TextField(db_column="cargo_responsavel")),
                (
                    "email",
                    models.EmailField(db_column="email_responsavel", max_length=254),
                ),
                ("nro_cpf", models.TextField(db_column="nro_cpf_responsavel")),
                ("telefone", models.TextField(db_column="telefone_responsavel")),
                (
                    "insert",
                    models.DateTimeField(
                        db_column="date_time_insert", default=django.utils.timezone.now
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
            ],
            options={
                "db_table": "wms_empresa",
            },
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id_endereco",
                    models.AutoField(
                        db_column="id_endereco", primary_key=True, serialize=False
                    ),
                ),
                ("rua", models.CharField(max_length=255)),
                ("numero", models.CharField(blank=True, max_length=10, null=True)),
                ("cidade", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=50)),
                ("codigo_postal", models.CharField(max_length=15)),
                ("descricao", models.TextField()),
                (
                    "insert",
                    models.DateTimeField(
                        db_column="date_time_insert", default=django.utils.timezone.now
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
            ],
            options={
                "db_table": "wms_endereco",
            },
        ),
        migrations.CreateModel(
            name="Galao",
            fields=[
                ("data_insercao", models.DateTimeField()),
                ("data_atualizacao", models.DateTimeField(null=True)),
                ("data_validade", models.CharField(max_length=50)),
                ("data_fabricacao", models.CharField(max_length=50)),
                ("descricao", models.TextField(null=True)),
                (
                    "id_galao",
                    models.AutoField(
                        db_column="id_galao", primary_key=True, serialize=False
                    ),
                ),
                (
                    "insert",
                    models.DateTimeField(
                        db_column="date_time_insert", default=django.utils.timezone.now
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
            ],
            options={
                "db_table": "wms_galao",
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id_cliente",
                    models.AutoField(
                        db_column="id_cliente", primary_key=True, serialize=False
                    ),
                ),
                ("nome_cliente", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=20)),
                ("ultima_compra", models.DateField()),
                ("tipo_cliente", models.CharField(max_length=50)),
                ("insert", models.DateTimeField(db_column="date_time_insert")),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        db_column="fk_endereco",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.endereco",
                    ),
                ),
            ],
            options={
                "db_table": "wms_cliente",
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id_loja",
                    models.AutoField(
                        db_column="id_loja", primary_key=True, serialize=False
                    ),
                ),
                ("nome_loja", models.CharField(db_column="nome_loja", max_length=255)),
                (
                    "endereco",
                    models.CharField(db_column="endereco", max_length=255, null=True),
                ),
                (
                    "numero_telefone",
                    models.CharField(
                        db_column="numero_telefone", max_length=15, null=True
                    ),
                ),
                (
                    "horario_operacao",
                    models.CharField(
                        db_column="horario_operacao", max_length=50, null=True
                    ),
                ),
                ("insert", models.DateTimeField(db_column="date_time_insert")),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="fk_empresa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "wms_loja",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(db_column="nome_produto", max_length=255)),
                (
                    "quantidade_estoque",
                    models.IntegerField(db_column="quantidade_estoque"),
                ),
                ("tipo", models.IntegerField(db_column="tipo_produto")),
                ("insert", models.DateTimeField(db_column="date_time_insert")),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "preco_compra",
                    models.DecimalField(
                        db_column="preco_compra", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "preco_venda",
                    models.DecimalField(
                        db_column="preco_venda", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "fabricante",
                    models.CharField(db_column="fabricante", max_length=100),
                ),
                ("descricao", models.TextField(db_column="descricao")),
                (
                    "loja",
                    models.ForeignKey(
                        db_column="fk_loja",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.loja",
                    ),
                ),
            ],
            options={
                "db_table": "wms_produto",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id_usuario",
                    models.AutoField(
                        db_column="id_usuario", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(db_column="nome_completo", max_length=255),
                ),
                (
                    "nome_usuario",
                    models.CharField(db_column="nome_usuario", max_length=50),
                ),
                ("senha", models.CharField(db_column="senha", max_length=50)),
                (
                    "insert",
                    models.DateTimeField(
                        db_column="date_time_insert", default=django.utils.timezone.now
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                ("nivel_usuario", models.IntegerField(db_column="nivel_usuario")),
                (
                    "status_acesso",
                    models.BooleanField(db_column="status_acesso", default=False),
                ),
                ("email", models.EmailField(db_column="email", max_length=255)),
                (
                    "ultimo_login",
                    models.DateTimeField(db_column="ultimo_login", null=True),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        db_column="fk_empresa",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.empresa",
                    ),
                ),
            ],
            options={
                "db_table": "wms_usuario",
            },
        ),
        migrations.CreateModel(
            name="SessaoUsuario",
            fields=[
                (
                    "id_sessao",
                    models.AutoField(
                        db_column="id_sessao", primary_key=True, serialize=False
                    ),
                ),
                ("ip_sessao", models.CharField(db_column="ip_sessao", max_length=100)),
                ("descricao", models.CharField(db_column="descricao", max_length=100)),
                (
                    "pagina_atual",
                    models.CharField(db_column="pagina_atual", max_length=200),
                ),
                (
                    "time_iniciou",
                    models.DateTimeField(
                        db_column="time_finalizou", default=django.utils.timezone.now
                    ),
                ),
                ("status", models.BooleanField(db_column="status", default=True)),
                (
                    "insert",
                    models.DateTimeField(
                        db_column="date_time_insert", default=django.utils.timezone.now
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="fk_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "wms_sessao_usuario",
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_venda", models.DateField(db_column="data_venda")),
                (
                    "valor_total",
                    models.DecimalField(
                        db_column="valor_total", decimal_places=2, max_digits=10
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(db_column="forma_pagamento", max_length=50),
                ),
                ("tipo_venda", models.CharField(db_column="tipo_venda", max_length=20)),
                ("insert", models.DateTimeField(db_column="date_time_insert")),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                ("descricao", models.TextField(db_column="descricao")),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="fk_cliente",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.cliente",
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        db_column="fk_loja",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.loja",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="fk_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "wms_venda",
            },
        ),
        migrations.CreateModel(
            name="GestaoGalao",
            fields=[
                (
                    "id_gestao_galao",
                    models.AutoField(
                        db_column="id_gestao_galao", primary_key=True, serialize=False
                    ),
                ),
                ("insert", models.DateTimeField(db_column="date_time_insert")),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        db_column="fk_cliente",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.cliente",
                    ),
                ),
                (
                    "galao_entrando",
                    models.ForeignKey(
                        db_column="fk_galao_entrando",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galao_entrando_set",
                        to="app.galao",
                    ),
                ),
                (
                    "galao_saiu",
                    models.ForeignKey(
                        db_column="fk_galao_saiu",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="galao_saiu_set",
                        to="app.galao",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        db_column="fk_venda",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.venda",
                    ),
                ),
            ],
            options={
                "db_table": "wms_gestaogalao",
            },
        ),
        migrations.CreateModel(
            name="VendaProduto",
            fields=[
                ("quantidade", models.IntegerField()),
                (
                    "id_venda_produto",
                    models.AutoField(
                        db_column="id_venda_produto", primary_key=True, serialize=False
                    ),
                ),
                ("insert", models.DateTimeField(db_column="date_time_insert")),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        db_column="fk_produto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        db_column="fk_venda",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.venda",
                    ),
                ),
            ],
            options={
                "db_table": "wms_venda_produto",
            },
        ),
    ]
