# Generated by Django 5.0.2 on 2024-03-12 16:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessao",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="sessao",
            name="descricao",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="sessao",
            name="pagina_atual",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sessao",
            name="time_iniciou",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
