# Generated by Django 5.0.2 on 2024-03-13 18:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id_configuracao",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.TextField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("descricao_interna", models.TextField(blank=True, null=True)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("status_acesso", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
        ),
    ]
