# Generated by Django 5.0.2 on 2024-04-16 17:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="id",
        ),
        migrations.AddField(
            model_name="cliente",
            name="id_cliente",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
