# Generated by Django 5.0.2 on 2024-02-20 18:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessao",
            fields=[
                (
                    "id_sessao",
                    models.AutoField(
                        db_column="id_sessao", primary_key=True, serialize=False
                    ),
                ),
                ("ip_sessao", models.CharField(db_column="ip_sessao", max_length=100)),
                ("descricao", models.CharField(db_column="descricao", max_length=100)),
                (
                    "pagina_atual",
                    models.CharField(db_column="pagina_atual", max_length=200),
                ),
                (
                    "time_iniciou",
                    models.DateTimeField(
                        db_column="time_finalizou", default=django.utils.timezone.now
                    ),
                ),
                ("status", models.BooleanField(db_column="status", default=True)),
                (
                    "insert",
                    models.DateTimeField(
                        db_column="date_time_insert", default=django.utils.timezone.now
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(db_column="date_time_update", null=True),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="fk_usuario",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "wms_sessao",
            },
        ),
        migrations.DeleteModel(
            name="SessaoUsuario",
        ),
    ]
