# Generated by Django 5.0.4 on 2024-04-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="endereco",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.endereco",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="update",
            field=models.DateTimeField(null=True),
        ),
    ]
