# Generated by Django 5.0.2 on 2024-03-01 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                db_column="fk_endereco",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.endereco",
            ),
        ),
    ]
