# Generated by Django 5.0.4 on 2024-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_cliente_endereco_alter_loja_endereco_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="data_validade",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
