# Generated by Django 5.0.2 on 2024-02-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_sessao_delete_sessaousuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="senha",
            field=models.CharField(db_column="senha", max_length=200),
        ),
    ]
