# Generated by Django 5.0.4 on 2024-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_associado_insert_alter_associado_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="data_venda",
            field=models.CharField(
                default="14/05/2024", editable=False, max_length=100
            ),
        ),
    ]
