# Generated by Django 5.0.2 on 2024-03-10 02:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_historico_sessao_cidade_sessao_codigo_postal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="endereco",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
