# Generated by Django 5.0.2 on 2024-03-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_sessao_latitude_remove_sessao_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessao",
            name="descricao",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
