# Generated by Django 5.0.2 on 2024-03-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_remove_loja_horario_operacao_loja_domingo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loja",
            name="horario_operacao_fim",
            field=models.TimeField(
                blank=True, db_column="horario_operacao_fim", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="horario_operacao_inicio",
            field=models.TimeField(
                blank=True, db_column="horario_operacao_inicio", null=True
            ),
        ),
        migrations.AlterField(
            model_name="loja",
            name="numero_telefone",
            field=models.CharField(
                db_column="numero_telefone", max_length=50, null=True
            ),
        ),
    ]
