# Generated by Django 5.0.4 on 2024-05-14 14:03

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_venda_data_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="data_venda",
            field=models.CharField(
                default=app.utils.utils.obter_data_hora_atual,
                editable=False,
                max_length=100,
            ),
        ),
    ]
