# Generated by Django 5.0.2 on 2024-03-17 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_produto_codigo_associados_loja_associados"),
    ]

    operations = []
