# Generated by Django 5.0.2 on 2024-04-19 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_venda_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gestaogalao",
            name="cliente",
        ),
    ]
