# Generated by Django 5.0.4 on 2024-04-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_associado_insert_alter_associado_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
