# Generated by Django 5.0.4 on 2024-05-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_venda_data_venda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.usuario",
            ),
        ),
    ]
