# Generated by Django 5.0.2 on 2024-03-18 14:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_auto_20240317_1203"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loja",
            name="associados",
        ),
        migrations.AddField(
            model_name="produto",
            name="codigo",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Associado",
            fields=[
                (
                    "id_associado",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "update",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("status_acesso", models.BooleanField(default=True)),
                (
                    "loja",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.loja",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.usuario",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Associados",
        ),
    ]
