# Generated by Django 5.0.4 on 2024-04-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_produto_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
