# Generated by Django 5.0.2 on 2024-03-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_loja_associados_produto_codigo_associado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associado",
            name="status_acesso",
            field=models.BooleanField(null=True),
        ),
    ]
