# Generated by Django 5.0.2 on 2024-03-25 14:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_associado_status_acesso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motoboy",
            fields=[
                (
                    "id_motoboy",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=20)),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="venda",
            name="id",
        ),
        migrations.AddField(
            model_name="venda",
            name="estado_transacao",
            field=models.CharField(default="pendente", max_length=20),
        ),
        migrations.AddField(
            model_name="venda",
            name="id_venda",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="metodo_entrega",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="numero_transacao",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="data_venda",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="venda",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="insert",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="venda",
            name="update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id_compra",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_compra", models.DateField(default=django.utils.timezone.now)),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("forma_pagamento", models.CharField(max_length=50)),
                (
                    "estado_transacao",
                    models.CharField(default="pendente", max_length=20),
                ),
                (
                    "numero_transacao",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "metodo_entrega",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.cliente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCompra",
            fields=[
                (
                    "id_item_compra",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(blank=True, null=True)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.compra"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.produto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="produtos",
            field=models.ManyToManyField(through="app.ItemCompra", to="app.produto"),
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id_entrega",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor_entrega", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "data_pedido",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_finalizacao", models.DateTimeField(blank=True, null=True)),
                (
                    "venda",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrega",
                        to="app.venda",
                    ),
                ),
                (
                    "motoboy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.motoboy",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VendaProduto",
        ),
    ]
