# Generated by Django 5.0.2 on 2024-03-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_motoboy_remove_venda_id_venda_estado_transacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venda",
            name="numero_transacao",
        ),
        migrations.RemoveField(
            model_name="venda",
            name="tipo_venda",
        ),
        migrations.AddField(
            model_name="venda",
            name="nota_fiscal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="troco",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="valor_pago",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="estado_transacao",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="venda",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="estado_transacao",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
