# Generated by Django 5.0.4 on 2024-06-20 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_empresa_id_remove_usuario_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalizacao",
            old_name="id",
            new_name="id_personalizacao",
        ),
    ]
