# Generated by Django 5.0.2 on 2024-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_remove_venda_numero_transacao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="tipo",
        ),
        migrations.AddField(
            model_name="produto",
            name="data_validade",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="is_retornavel",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
