# Generated by Django 5.0.2 on 2024-04-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_produto_tipo_produto_data_validade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="descricao_cliente",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="tipo_cliente",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="ultima_compra",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="cliente",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.cliente"
            ),
        ),
    ]
