# Generated by Django 5.0.2 on 2024-04-02 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_cliente_descricao_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motoboy",
            name="empresa",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.empresa"
            ),
        ),
        migrations.CreateModel(
            name="Caixa",
            fields=[
                (
                    "id_caixa",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insert", models.DateTimeField(default=django.utils.timezone.now)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "saldo_inicial",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "saldo_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.loja"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "caixa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.caixa"
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.venda",
                    ),
                ),
            ],
        ),
    ]
