# Generated by Django 5.0.2 on 2024-04-03 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_motoboy_empresa_caixa_transacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="galao",
            name="loja",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.loja"
            ),
        ),
        migrations.AddField(
            model_name="galao",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="galao",
            name="titulo",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="gestaogalao",
            name="descricao",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="galao",
            name="data_fabricacao",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="galao",
            name="data_insercao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="galao",
            name="data_validade",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
