# Generated by Django 5.0.2 on 2024-04-12 18:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_galao_loja_galao_quantidade_galao_titulo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemcompra",
            name="compra",
        ),
        migrations.RemoveField(
            model_name="entrega",
            name="data_finalizacao",
        ),
        migrations.RemoveField(
            model_name="entrega",
            name="data_pedido",
        ),
        migrations.RemoveField(
            model_name="galao",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="galao",
            name="data_insercao",
        ),
        migrations.RemoveField(
            model_name="itemcompra",
            name="preco_unitario",
        ),
        migrations.RemoveField(
            model_name="transacao",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="entrega",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrega",
            name="insert",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="entrega",
            name="time_finalizacao",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrega",
            name="time_pedido",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entrega",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="itemcompra",
            name="venda",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.venda"
            ),
        ),
        migrations.AddField(
            model_name="transacao",
            name="insert",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transacao",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="desconto",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="produtos",
            field=models.ManyToManyField(
                blank=True, null=True, through="app.ItemCompra", to="app.produto"
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="valor_entrega",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="saldo_inicial",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="bairro",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="cidade",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="codigo_postal",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="endereco",
            name="estado",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="gestaogalao",
            name="insert",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="itemcompra",
            name="produto",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.produto"
            ),
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
    ]
