# Generated by Django 5.0.4 on 2024-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_id_personalizacao_id_personalizacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdv",
            name="status_operacao",
            field=models.IntegerField(
                choices=[
                    (0, "Bloqueado"),
                    (1, "Excluído"),
                    (2, "Aberto"),
                    (3, "Fechado"),
                ],
                default=3,
            ),
        ),
    ]
