# Generated by Django 5.0.4 on 2024-06-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_transacaopdv_tipo_operacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transacaopdv",
            name="usuario",
        ),
        migrations.AddField(
            model_name="registrodiariopdv",
            name="descricao_interna",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="transacaopdv",
            name="tipo_pagamento",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Dinheiro"),
                    (2, "Máquina de Crédito"),
                    (3, "Máquina de Débito"),
                    (4, "PIX"),
                    (5, "Fiado"),
                    (6, "Boleto"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="tipo_pagamento",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Dinheiro"),
                    (2, "Máquina de Crédito"),
                    (3, "Máquina de Débito"),
                    (4, "PIX"),
                    (5, "Fiado"),
                    (6, "Boleto"),
                ],
                null=True,
            ),
        ),
    ]
